MODULE	= formatter

EXE			= lib$(MODULE).so

INCLUDE	= \
					-I../media/src/include \
					-I../tuner/src/include \
					-I/usr/local/include/fusionsound \

CFLAGS	+= -shared -fPIC

OBJS 		= \
					nclaudioplayer.o\
					ncldisplay.o\
					nclenviroment.o\
					nclevent.o\
					nclexception.o\
					ncletplayer.o\
					nclformatter.o\
					nclhelper.o\
					nclimageplayer.o\
					nclinput.o\
					nclselectionevent.o\
					ncleventlistener.o\
					nclloader.o\
					nclobject.o\
					nclplayer.o\
					nclpresentationevent.o\
					ncltextplayer.o\
					ncltimer.o\
					ncltimerevent.o\
					ncltimerlistener.o\
					nclvideoplayer.o\
					nclxhtmlplayer.o\
					nclluaplayer.o\
					nclluacanvas.o\
					nclluaevent.o\
					nclluasettings.o\
					nclluaobjectbinding.o\

include ../../Makefile.defs
include ../../Makefile.build
