MODULE	= tuner

EXE			= lib$(MODULE).so

CFLAGS	+= -shared

OBJS 		= \
					channel.o \
					filechannel.o \
					filemediabank.o \
					filetuner.o \
					ipchannel.o \
					ipmediabank.o \
					iptuner.o \
					jtunerlib.o \
					locator.o \
					mediabank.o \
					tuner.o \
					tunerevent.o \
					tunerexception.o \
					tunerlistener.o \
					tunermanager.o \
					tunerstatusevent.o \
					tunerstatuslistener.o \
	   
include ../../Makefile.defs
include ../../Makefile.build

